---
title: "Annotated Bibliography"
author: "Zimbabwe Project"
date: "6/7/2021"
output:
  html_document:
    toc: true
    toc_float:
      collapsed: false
      smooth_scroll: true
---

```{r setup, include=FALSE}
knitr::opts_chunk$set(echo = TRUE)
```

# Yang Cheng 

## Multidimensional Poverty in Crisis: Lessons from Zimbabwe [PDF](https://doi-org.ezproxy.lib.vt.edu/10.1080/00220388.2015.1087511)

Quentin Stoeffler, Jeffrey Alwang, Bradford Mills & Nelson Taruvinga

During the first decade of the twenty-first century, Zimbabwe experienced a sharp social, political, and economic crisis, but is now on a recovery path.  Since February 2009, inflation has been under control and economic growth has returned, although the recovery is still regarded as fragile. The macroeconomic causes and the economy-wide impact of the crisis have been documented (Hanke, 2012; Mashakada, 2013; Ndlela, 2011), along with the impact of land reform on the wellbeing of different household groupings (Scoones et al., 2010). However, the evolution of household wellbeing and its different dimensions during and after the crisis have not been fully investigated. It is unclear how the economic crisis and subsequent recovery impacted various dimensions of household wellbeing, such as access to education and public services, health, or income/consumption. This paper fills this gap by analysing changes in multidimensional indicators of poverty between 2001, 2007 and 2011–2012 using the nationally representative household Incomes, Consumption, and Expenditure Surveys (ICES) and Poverty, Income, Consumption, and Expenditure Survey (PICES). This paper extends the MPI analysis in several ways. First, it provides a comparative multidimensional poverty measure before, during, and after the crisis. Second, it employs ICES/PICES datasets that allow examination of more deprivation dimensions than is possible with the DHS. Inclusion of additional dimensions enables construction of an index adapted to the Zimbabwean context. Third, the multidimensional poverty measure permits adjustment of deprivation thresholds to reflect the Zimbabwean reality, including urban and rural differences in poverty dimensions. Multidimensional indices aggregate deprivations encountered by households – accounting for the number of individuals in households – to form a picture of the complex evolution of poverty from 2001 to 2011–2012.5 The index employed in this paper, based on the Alkire–Foster (A–F) method (Alkire & Foster, 2011a), is decomposed by dimension and geographic area to identify key factors affecting deprivation. Results show a clear increase in multidimensional poverty from 2001 to 2007, and then a decrease from 2007 to 2011–2012, leaving an ambiguous overall change in poverty from 2001 to 2011–2012. The results are robust to alternative specifications. Changes in individual dimensions do not always follow overall changes, highlighting different dynamics in poverty dimensions that should be considered in the design of poverty alleviation and recovery efforts. For instance, access to electricity and some human capital indicators actually improved through the 2000s. In contrast, health indicators and ownership of livestock in rural areas declined even in the recovery period, while access to services declined and then recovered. This paper is limited in the respect that it does not give a concise explanation of how to mathematically combine the dimensions it describes so thoroughly. Furthermore, it uses very simple weighting; it makes the assumption that in most of these categories, individuals in urban areas are half as poor as those in rural areas, or two thirds as poor, which seems to be an arbitrary mathematical convenience rather than an evidence-based strategy. Due to this kind of false dichotomy and oversimplification, this algorithm in this paper threatens to mask the needs of Zimbabwe’s population.

# Atticus Rex
## Counting and multidimensional poverty measurement [PDF](https://doi.org/10.1016/j.jpubeco.2010.11.006)

Sabina Alkire, James Foster

In 2011, Sabina Alkire and James Foster attempt to provide a baseline framework for assessing poverty across multiple dimensions. The overall goal of this paper was to provide a way to quantify poverty for individuals within a certain region across an undefined range of dimensions. The value to our research in this paper comes from the mathematical methodology. This paper derives a measure called the headcount ratio, which is the ratio of designated "poor" people to the entire population. Subsequently, the paper delves into what it calls the Adjusted Headcount Ratio in which it takes into account the dimensionality of poverty to provide a more nuanced view of the measure. While presented in a wholly convoluted and inconcise way, the methodology used at the core of this paper was quite simple. The mathematics provide a standardized threshold system that forms the basis of the paper pertaining specifically to Zimbabwe. It is also quintessential to make note of the fact that since this paper has been published one decade prior to the creaiton of this bibliography, the accepted multidimensional poverty index has changed substantially and become far more standardized throughout the world, aided by the United Nations. The currently accepted model for multidimensional poverty, ordained by Sabina Alkire, looks nothing like the model described in this paper. Furthermore, this paper seeks a framework to assess poverty in a more multidimensional and scalable way, but at the end of the day, it does not take a weighted average of the dimensions; it simply assigns a threshold algorithm and designates an individual as “poor” or “not poor” and then takes the average of the whole population as a result of that to produce a figure that looks nuanced. The paper explores other avenues of potentially creating a more reflective representation of dimensinoal poverty with the Adjusted head Count and the Poverty Gap measurements, but for a paper whose overall goal is to provide a unilateral reflection of poverty across multiple different facets of human life, the results are convoluted at best. 

# Atticus Rex 
## Zimbabwe’s Recovery Path: A Conceptual Framework [PDF](https://www.sahistory.org.za/sites/default/files/file%20uploads%20/hany_besada_zimbabwe_picking_up_the_piecesbook4you.pdf)

Hany Besada and Jason LaChapelle

This chapter of Hany Besada’s book helps to lend perspective to Zimbabwe’s political and economic contexts during the 21st century. It is the first chapter of the book and helps to provide a lot of historical consideration for further study. The value in this text comes from understanding Zimbabwe’s economic and social trajectory coming out of the year 2011 when the last PICES data was collected. We have a lot of information available to us and when coming up with a multidimensional index, it is important to keep in mind contextual and cultural realities that might make certain measures less effective. As described in other sources, the Zimbabwean currency is an unreliable and inconsistent measure of economic assets because of the hyperinflation in the 2000's era. This text covers the history of Zimbabwe from its independence from the United Kingdom in 1980 to 2011 when the source was published. This period includes periods of intense political strife, governmental corruption, foreign aid and massive debt, assessments of human rights initiatives and qualitative accounts of asset distribution within the state. This source gives no indication of how to actually measure poverty, nor any technical aspects of our research. It is also over a decade old and the cultural contexts of Zimbabwe have changed rather substantially throughout the last ten years and this perspective is  likely to be outdated when considering what has occurred geopolitically in the subsequent years.

# Matthew Burkholder
## Measuring Acute Poverty in the Developing World: Robustness and Scope of the Multidimensional Poverty Index
[Link](https://reader.elsevier.com/reader/sd/pii/S0305750X14000278?token=3815C1BC84E3A1A1D245A801F981151F6E948AFD033F628EC2EF7DB41F96D110736462BDC596410EA17FAACCDAF7B13A&originRegion=us-east-1&originCreation=20210609132956)

Sabina Alkire & Maria Emma Santos


To make clear the methodology behind DSPG’s work, this review will first examine literature surrounding the composition and use of multidimensional poverty indices in developing countries. Here, a review of Sabina Alkire and Maria Emma Santo’s work surrounding the effectiveness of the global MPI in measuring acute poverty will be helpful. Their article first delineates the construction of a MPI. Inspired largely by Amartya Sen’s work, emplyment of a MPI takes a ‘direct’ approach to measuring poverty in the sense that it seeks to determine whether people have the ability to satisfy basic needs as opposed to determining whether they receive a certain income. The work notes that this approach, and their MPI in particular, is advantageous because it accounts for discrepancies in areas such as consumption, prices, functioning, market differences and household income distribution. By breaking poverty into three dimensions (Education, Health, Living Standard) with ten weighted and corresponding indicators (Nutrition, Child Mortality, Years of Schooling, School Attendance, Cooking Fuel, Sanitation, Water, Electricity, Floor, Assets), their MPI provides a consistent and deconstructable measure of poverty. The authors utilized the MPI to assess 104 countries and determined that the world’s MPI poor are located in South America (49%) and Sub-Saharan Africa (27%). They additionally used the MPI to calculate the intensity of poverty, revealing the average percentage of deprivation in each country. Because this intensity is accounted for in the total MPI value, countries with similar poverty incidence but greater intensity output more severe MPI values. Overall,the study showed that the MPI is an extremely advanced and effective tool that can be wielded to highlight overall poverty and, most importantly, acute poverty at district levels. It also highlighted certain data constraints faced when implementing an MPI, most notably in the categories of dimensions, comparability, and unit of analysis.

# Matthew Burkholder
## The Hyperinflation in Zimbabwe 
[Link](http://mises-media.s3.amazonaws.com/qjae14_3_3.pdf)

Jayson Coomer & Thomas Gstraunthaler

Before investigating the practicality of a multidimensional poverty index to assess district specific poverty in Zimbabwe, it is necessary to understand the country’s economic evolution. The Hyperinflation in Zimbabwe, a journal article compiled by Jayson Coomer and Thomas Gstraunthaler, proves especially helpful in contextualizing Zimbabwe’s present situation. In this work, the two utilize data collected by the United Nations and the International Monetary Fund (IMF) as a means of crafting a historical report of the events that contributed to Zimbabwe’s economic crisis and significant inflation rates. They found that in 1997, seventeen years after Zimbabwe won independence from Britain, the government began to provide veteran pensions and to make compulsory purchases of white-owned, commercial farmland. While these actions satisfied a growing public demand, they lacked sufficient financing and thus put the government budget in deficit. At the same time, these policies gave rise to inflation as veterans continued to receive and spend government funded pensions. The combination of these negative economic indicators sparked panic among investors, the loss of foreign capital, and the eventual crash of the Zimbabwean dollar. A combination of the government printing increasingly more money to mitigate the damage and the formation of a parallel black market caused Zimbabwe to suffer from sever hyperinflation. This trend continued until the country dollarized in 2009 and began to exhibit a three percent month-on-month decline. The effects of this crisis, however, have been long lasting and are largely responsible for modern day economic hardship in Zimbabwe.

**MLA citations**

## Reference 
1. Stoeffler, Quentin, et al. "Multidimensional poverty in crisis: Lessons from Zimbabwe." The journal of development studies 52.3 (2016): 428-446.
2. Alkire, Sabina, and James Foster. “Counting and Multidimensional Poverty Measurement.” Journal of Public Economics, vol. 95, no. 7-8, 2011, pp. 476–487., doi:10.1016/j.jpubeco.2010.11.006.
3. Besada, Hany, and Jason LaChapelle. “Zimbabwe’s Recovery Path: A Conceptual Framework.” Zimbabwe, 2011, pp. 1–9., doi:10.1057/9780230116436_1.
4. Alkire, S., & Santos, M. "Measuring Acute Poverty in the Developing World: Robustness and Scope of the Multidimensional Poverty Index." World Development 59 (2014): 251-274.
5. Coomer, J., & Gstraunthaler. "The Hyperinflation in Zimbabwe." Quarterly journal of Australian economics 14.3 (2011): 311-346.
