---
title: "Methodology MPI AF"
author: "Zimbabwe Project"
date: "6/11/2021"
output:
  html_document:
    toc: true
    toc_float:
      collapsed: false
      smooth_scroll: true
---

```{r setup, include=FALSE}
knitr::opts_chunk$set(echo = TRUE)
```


# Matthew Burkholder

A Multidimensional Poverty Index (MPI) is tool that determines levels of poverty by measuring the capability of individuals to satisfy a determined set of needs rather than the income they receive. MPIs are comprised of separate poverty dimensions that demarcate the areas in which poverty most prominently manifests. Each dimension is accompanied by certain indicators that imply a population’s status in said dimension. As data is analyzed, it is categorized by indicator and, therefore, by the larger dimension which encompasses each indicator. Each dimension is weighted on the grounds of how important it is to the wellbeing of the study/survey’s participants. A threshold level of deprivation is set such that individuals that fall under said threshold are considered poor and those above are not considered poor. When an MPI is applied, a decision must be made regarding conceptions of poverty. The ‘union approach’ defines a household as impoverished if they fall below the threshold level of deprivation in any one of the MPI’s dimensions. The ‘intersection approach’, alternatively, defines a household as impoverished if they fall below the threshold level of deprivation in all dimensions. A third tactic, the ‘counting approach’, combines the aforementioned approaches and thus defines a household as impoverished if they are deprived anywhere between one or all of the dimensions. The Alkire-Foster, or AF, approach utilizes this third technique and employs a double cut-off in the identification process: A household is deprived in a dimension if they fall below the set threshold of said dimension and are poor if the sum of their deprivation is greater than the overall MPI threshold level. This technique allows for sort of weeding process in which only those who are broadly categorized as poor are factored in to the MPI value and those who are not poor but are somewhat deprived are not factored in at all. The main value, M0, is then a product of H, the ratio of poor in relation to the overall population, multiplied by A, the average deprivation share among this poor population. This approach is useful because it allows for multiple dimensions of poverty to be measured in a single metric and enables the impact of individual dimensions on overall index change to be identified through decomposition of the MPI. MPIs can also be uniquely beneficial insofar as they reveal intensity of poverty at both acute and more general levels both inside and among poverty dimensions.



# Atticus Rex

The aggregate methodology for determining the multidimensional poverty indices proposed by Alkine and Foster in 2011 involve a matrix with *n* rows and *d* columns, where *n* is the number of people within the state and *d* is the number of dimensions for assessing poverty. There are three main measurements denoted the "*M*" scale: *M0, M1 and M2*. 

* **M0**: This is the main poverty index for determining a group's poverty. This is calculated by multiplying the Headcount Ratio, *H*, with the Average Deprivation Share. The Headcount Ratio is the number of people who are considered poor based on a threshold, *k*. The Average Deprivation Share is the number of actual deprivations collected from each dimension divided by the number of potential deprivations that the state could have. In our case, this is the sum of the weights of each dimension multiplied by the population of the country. 
* **M1**: This is a measure of the Adjusted Poverty Gap. This measure is obtained by taking the average of the gaps of poor individuals below some poverty line, *k*. If the individual is above this threshold, *k*, their poverty gap is zero. Otherwise, it is always positive. This ensures that the needs of poor people do not become weighed down by their more wealthy counterparts. 
* **M2**: This is a measure of the Adjusted Poverty Severity. This measure is obtained by taking the average of the square of the gaps of poor individuals below some poverty line, *k*. It is very similar to *M1*, the only difference is that the poverty gap is squared. The quadratic nature of this measurement helps to give more weight to the people who are significantly below the poverty line as opposed to those who fall just beneath it. 

These are the main metrics that will inform our geographical interpretation of the PICES data. It is also important to discuss the dimensions of poverty that will form the number of deprivations in our study. The dimensions include Education, Health, Employment, Housing Conditions, Living Conditions, Assets, Agricultural Assets (Only applies to those living in Rural areas) and Access to Services. It is also important to note that if the individual lives in a rural area, he or she has more possible deprivations than someone living in an urban area. These dimensions are broken down into a couple of variables which have certain weights in determining how much of the overall dimension weight it accounts for. Many of the variables are binary as simple yes or no questions, but some of them are also continuous. With the continuous ones, we will be using threshold algorithms provided by Stoeffler et al. to assess whether or not the individual is considered poor within this variable. (*Author's Note: I believe this is a counterproductive methodology because continuous variables can provide more nuanced data and do not have to be dichotomized into a "poor" or "not poor" relationship. If we used a sigmoid-type function to scale the values into the preferred weight range, we could come up with more accurate measures, but I digress.) 

**Headcount Ratio**

$H = \frac{n_{poor}}{n_{pop}}$

**Average Deprivation Share**

$A = \frac{n_{deprivations}}{n_{potential}}$

**Deprivation Threshold**

$k$ = *Threshold (If an index is above threshold, k, then the individual is considered poor)*

**Poverty Index**

$M_{0} = H*A$

**Adjusted Poverty Gap**

$M_{1} = μ(g^{1}(k))$

$g^{1}_{i} = k - \frac{\sum deprivations}{\sum possible\ deprivations}$ *if* $g^{1}_{i} > 0$

$else\ g^{1}_{i} = 0$


**Adjusted Poverty Severity**

$M_{2} = μ(g^{2}(k))$

$g^{2}_{i} = [k - \frac{\sum deprivations}{\sum possible\ deprivations}]^{2}$ *if* $g^{2}_{i} > 0$

$else\ g^{2}_{i} = 0$

**Dimensional Aggregation**

$Deprivation_{total} = \sum_{i=1}^{d}\sum_{j=1}^{v_{d}} w_{i, j}$

$d =$ *number of dimensions*

$v_{d}$ = *number of variables for a specific dimension*

$w_{i,j}$ = *weight of a specific variable for a specific dimension*
