---
title: "Methodology MPI AK"
author: "Zimbabwe Project"
date: "6/11/2021" 
output:
  html_document:
    toc: true
    toc_float:
      collapsed: false
      smooth_scroll: true
---

```{r setup, include=FALSE}
knitr::opts_chunk$set(echo = TRUE)
```


# Yang Cheng

*Few sentences*


# Atticus Rex

The aggregate methodology for determining the multidimensional poverty indices proposed by Alkine and Foster in 2011 involve a matrix with *n* rows and *d* columns, where *n* is the number of people within the state and *d* is the number of dimensions for assessing poverty. There are three main measurements denoted the "*M*" scale: *M0, M1 and M2*. 

* **M0**: This is the main poverty index for determining a group's poverty. This is calculated by multiplying the Headcount Ratio, *H*, with the Average Deprivation Share. The Headcount Ratio is the number of people who are considered poor based on a threshold, *k*. The Average Deprivation Share is the number of actual deprivations collected from each dimension divided by the number of potential deprivations that the state could have. In our case, this is the sum of the weights of each dimension multiplied by the population of the country. 
* **M1**: This is a measure of the Adjusted Poverty Gap. This measure is obtained by taking the average of the gaps of poor individuals below some poverty line, *k*. If the individual is above this threshold, *k*, their poverty gap is zero. Otherwise, it is always positive. This ensures that the needs of poor people do not become weighed down by their more wealthy counterparts. 
* **M2**: This is a measure of the Adjusted Poverty Severity. This measure is obtained by taking the average of the square of the gaps of poor individuals below some poverty line, *k*. It is very similar to *M1*, the only difference is that the poverty gap is squared. The quadratic nature of this measurement helps to give more weight to the people who are significantly below the poverty line as opposed to those who fall just beneath it. 

These are the main metrics that will inform our geographical interpretation of the PICES data. It is also important to discuss the dimensions of poverty that will form the number of deprivations in our study. The dimensions include Education, Health, Employment, Housing Conditions, Living Conditions, Assets, Agricultural Assets (Only applies to those living in Rural areas) and Access to Services. It is also important to note that if the individual lives in a rural area, he or she has more possible deprivations than someone living in an urban area. These dimensions are broken down into a couple of variables which have certain weights in determining how much of the overall dimension weight it accounts for. Many of the variables are binary as simple yes or no questions, but some of them are also continuous. With the continuous ones, we will be using threshold algorithms provided by Stoeffler et al. to assess whether or not the individual is considered poor within this variable. (*Author's Note: I believe this is a counterproductive methodology because continuous variables can provide more nuanced data and do not have to be dichotomized into a "poor" or "not poor" relationship. If we used a sigmoid-type function to scale the values into the preferred weight range, we could come up with more accurate measures, but I digress.) 

*H = (Headcount Ratio) # of poor people / population*
*A = (Average deprivation share) # of deprivations / # of potential deprivations*
*k = Threshold (If an index is above threshold, k, then the individual is considered poor)*

*M0 = Poverty Index (H x A) *
*M1 = Adjusted Poverty Gap (Mean(differences below poverty gap k))*
*M2 = Adjusted Poverty Severity (Squared Poverty Gap = Mean(differences squared below poverty gap k))*

*Dimension Weight = The number of deprivations possible in a particular dimension*
*Variable Weight = The part of the dimension weight responsible for a particular question*

*Total deprivation = Sum(Dimension Weights) where Dimension Weight = Sum(Variable Weights*



# Your Name